metadata:
  generator: herald
  generated_at: "2025-06-16T06:02:04Z"
  last_updated: "2025-06-16T06:15:32Z"

domains:
  example.com:
    comment: "Domain: example.com"
    records:
      - hostname: "@"
        type: A
        target: "192.168.1.100"
        ttl: 300
        created_at: "2025-06-16T06:02:04Z"
        source: herald

      - hostname: www
        type: CNAME
        target: example.com
        ttl: 300
        created_at: "2025-06-16T06:02:04Z"
        source: herald

      - hostname: api
        type: A
        target: "192.168.1.101"
        ttl: 120
        created_at: "2025-06-16T06:02:04Z"
        source: docker

      - hostname: mail
        type: A
        target: "192.168.1.102"
        ttl: 300
        created_at: "2025-06-16T06:02:04Z"
        source: traefik

      - hostname: "@"
        type: MX
        target: "10 mail.example.com"
        ttl: 3600
        created_at: "2025-06-16T06:02:04Z"
        source: herald

      - hostname: "@"
        type: TXT
        target: "v=spf1 mx ~all"
        ttl: 3600
        created_at: "2025-06-16T06:02:04Z"
        source: herald